# Generated by Django 3.2.19 on 2023-07-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230705_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='street_address1',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='county',
        ),
        migrations.RemoveField(
            model_name='event',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='town_or_city',
        ),
    ]
